# Generated by Django 2.1.1 on 2019-01-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_auto_20180911_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ker', models.DecimalField(decimal_places=2, max_digits=5)),
                ('no_of_working_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, max_digits=5)),
                ('testing_people', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PlanningData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FG_code', models.CharField(max_length=500)),
                ('DT_hrs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Product')),
            ],
        ),
    ]
