# Generated by Django 2.1.5 on 2019-02-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_headcount_planningdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningdata',
            name='yearly_product_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headcount',
            name='ker',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='headcount',
            name='no_of_working_days',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='headcount',
            name='testing_people',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='headcount',
            name='working_hours_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='planningdata',
            name='DT_hrs',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
