# Generated by Django 2.1.5 on 2019-02-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_planningdata_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningdata',
            name='month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2),
        ),
    ]
