# Generated by Django 2.1.5 on 2019-02-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_auto_20190204_0538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planningdata',
            options={'verbose_name_plural': 'Planning Data'},
        ),
        migrations.AddField(
            model_name='headcount',
            name='month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headcount',
            name='product_id',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='plant.Product'),
            preserve_default=False,
        ),
    ]
